#pragma config(Sensor, dgtl7,  ball_collected_limit, sensorDigitalIn)
#pragma config(Motor,  port10,          conveyor_driver, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int conveyor_speed = 100;

//SensorValue(ball_collected_limit) == 1   is unpressed
//SensorValue(ball_collected_limit) != 1   is pressed

void conveyor_start()
{
	motor(conveyor_driver) = conveyor_speed;
	writeDebugStreamLine("%s", "Conveyor Started/n");
}

// Conveyor will only reverse if ball has been collected
void conveyor_reverse()
{
		motor(conveyor_driver) = -conveyor_speed;
		writeDebugStreamLine("%s", "Conveyor Reversed/n");
}

// Stops the conveyor after reversing
void conveyor_stop()
{
	motor(conveyor_driver) = 0;
	writeDebugStreamLine("%s", "Conveyor Stopped/n");
}

task main()
{
	while(SensorValue(ball_collected_limit) == 1){
		conveyor_start();
	}

		conveyor_stop();
		delay(2000);
		conveyor_reverse();
		delay(2000);
		conveyor_stop();
		delay(2000);

}
