#pragma config(Sensor, in1,  sharp_sensor1,   sensorAnalog)
#pragma config(Sensor, in2,  sharp_sensor2,   sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Move to ball
int ball_in_collection_range ;
int collect_ball;
int enemy_in_range;


//Detect that distance sensor is at a small value means ball is detected
void go_to_ball(){

	while (1==1){
		if ((SensorValue(sharp_sensor1))< 1000 && (SensorValue(sharp_sensor2))>1000){ //both long and short sensoer must have value within range to trigger "Collect ball range"
			ball_in_collection_range = 1;
			writeDebugStreamLine("%d" ,"ball_in_collection_range");
		}

		else if (SensorValue(sharp_sensor1)> 1000){
			ball_in_collection_range =0;
		}

		else if ((SensorValue(sharp_sensor1))< 100 && (SensorValue(sharp_sensor2))<100){
			enemy_in_range = 1; // run enemy detection code?
		}
	}
	while (ball_in_collection_range ==1){
		//motor(left_motor) = 20; /

		if (SensorValue(sharp_sensor1)< 500 && SensorValue(sharp_sensor2)>1000){
			//activate belt for ball collection, break out of loop once ball collected
			collect_ball =1;
			writeDebugStreamLine("%d", collect_ball);
			//writeDebugStreamLine("%s" ,"Collecting ball");
		}
		else{
			//continue to move to ball
			motor(left_motor) = 20;
			motor(right_motor) = 20;
			//writeDebugStreamLine("%s" ,"Ball found, moving to ball");
			//writeDebugStreamLine("%d", colelct_ball);
		}


	} //While loop end
	while(ball_in_collection_range ==0){
		//continue searching for
		writeDebugStreamLine("%d" ,"ball_in_collection_range");
		return;
	}

	return;
}

task main(){
	while(1){
		go_to_ball();
		return;
	}
}
