#pragma config(Sensor, in2,    sharp_front_top, sensorAnalog)
#pragma config(Sensor, in3,    sharp_back_top, sensorAnalog)
#pragma config(Sensor, in7,    sharp_bl,       sensorAnalog)
#pragma config(Sensor, in8,    sharp_bs,       sensorAnalog)
#pragma config(Motor,  port2,           right_driver,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           left_driver,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,          conveyor_driver, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, in4, sharp_short, sensorAnalog)
//#pragma config(Sensor, in6, front_l_line, sensorAnalog) // why analog?
//#pragma config(Sensor, dgtl5, front_r_line, sensorDigitalIn)
//#pragma config(Sensor, dgtl11, back_l_line, sensorDigitalIn)
//#pragma config(Sensor, dgtl12, back_r_line, sensorDigitalIn)

#include "sensor.h"
#include "startup.c"
#include "searching_algorithm.c"

task main()
{
		startTask(sensor_calibration);
    first_move();
    sleep(1000);
    while(1)
        {
            if (ball_found == 1)
            {
                //writeDebugStreamLine("%s", "searching program ends");
                //return;
                // ball collecion mechanism activate here
            		sleep(5000);
            		motor(left_driver) = 60;
        				motor(right_driver) = 60;
            }
            else if (ball_found == 0)
            {

                spinning_search();
                if (ball_found == 0)
                {
                    writeDebugStreamLine("%s", "ball not found, move forward and repeat search");
                    move_forward();
                }
            }
        }
}
