#pragma config(Sensor, in2,    sharp_front2,      sensorAnalog)
#pragma config(Sensor, in3,    sharp_front3,      sensorAnalog)
#pragma config(Sensor, in7,    sharp_front1,      sensorAnalog)
#pragma config(Sensor, in8,    sharp_short,      sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int enemy_front_dist;
int enemy_back_dist;
float avg_efd;
float avg_ebd;
float total_efd;
float total_ebd;

int ball_long;
int ball_short;
float avg_bl;
float avg_bs;
float total_bl;
float total_bs;
int NUM_READINGS = 100;

task main(){
	while(1){

	total_efd = 0;
	total_ebd = 0;
	total_bl = 0;
	total_bs = 0;

	enemy_front_dist = SensorValue(sharp_front2);
	enemy_back_dist = SensorValue(sharp_front3);
	ball_long = SensorValue(sharp_front1)
	ball_short = SensorValue(sharp_short)

	for (int i = 0; i <= NUM_READINGS; i++) {
		total_efd += 29.98*pow((SensorValue(sharp_front2)*0.0012207031), -1.173);
		total_ebd += 29.98*pow((SensorValue(sharp_front3)*0.0012207031), -1.173);
		total_bl += 29.98*pow((SensorValue(sharp_front1)*0.0012207031), -1.173);
		total_bs += 29.98*pow((SensorValue(sharp_short)*0.0012207031), -1.173);
	}
	avg_efd = total_efd/NUM_READINGS;
	avg_ebd = total_ebd/NUM_READINGS;
	avg_bl = total_bl/NUM_READINGS;
	avg_bs = total_bs/NUM_READINGS;

	sleep(100);
	}
}
